os:
  - linux

language: node_js

node_js:
  - '8'

script:
  - npm run lint
  - npm test

after_failure:
  - ./bin/on_failure.sh

deploy:
  provider: npm
  email: vatev.1+npm@gmail.com
  skip_cleanup: true
  api_key:
    secure: Q1kbVn+DLATPDFpilrVx9BRrkpyz+/zLJ4L0hrtDdLcmuaxgg3c5pVYbtMnsrPDKlMEvd9Awqb3WBlwPQH5dus+8++T4PQWI+sMoZAkVtHyck6mp5nclAgaOVMHi4XOdL8O9uIHk5tgFdk/uXMq1xC3prNzYlIAyfygLOoqQbi8euARNTAj4i3R+pKgVVubwwGD7mHx4D+6DSATd7q5aR0ki//QAeVbZC9+7wVsOS4Zohu+80wXYiiEWaGoJCjVcq47KEzeQ1uh6db6eBe/ksF0IJZh7KaW/OCzJNTSr2gV8sis9VgG704k+4d7SDcq/seK4+B/HtH3K4s3wiuvVPwZQ5+NoohDG67N+jFKQWojd7xRXzdK90jnRYn69cvSZPTeCuBgtyRClOCEuv/kLVL/aImuNLzbAiX8BQtGcJcQQsEOSn8rFp43z2ghPCVDRelQb6CCEj2SxH2KwPB+TzFghjMjlv894lP4qs8A6NivkFk7NFjInKcdP5G989onYi8TLJKJf+x7tA/SXuKyBN4YMy6X4lLWSExuoslogfB1WN3b9EpYcZ7DtFOEcl/zzZfK+wvMgwfFbotrQCRyBN7UOrbx9R9biam0iL6tUw1bzCYQVtYkNjjMHjl7vwCL4iPxu1qeZmkGlLZpha0ADUpYlabxqkMcBEaiIJXaAWhw=
  on:
    tags: true
    repo: catdad/canvas-confetti
